version: '3'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus_multiclusters:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
      - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
      - "ENABLE_GLOBAL_DOMAIN=true"
      - "KEYSPACE=cadence_primary"
      - "VISIBILITY_KEYSPACE=cadence_visibility_primary"
      - "STATSD_FRONTEND_PREFIX=cadence-frontend-primary"
      - "STATSD_MATCHING_PREFIX=cadence-matching-primary"
      - "STATSD_HISTORY_PREFIX=cadence-history-primary"
      - "STATSD_WORKER_PREFIX=cadence-worker-primary"
    depends_on:
      - cassandra
      - prometheus
  cadence-secondary:
    image: ubercadence/server:master-auto-setup
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "7943:7933"
      - "7944:7934"
      - "7945:7935"
      - "7949:7939"
      - "7843:7833"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:9000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:9001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:9002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:9003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
      - "IS_NOT_PRIMARY=true"
      - "ENABLE_GLOBAL_DOMAIN=true"
      - "KEYSPACE=cadence_secondary"
      - "VISIBILITY_KEYSPACE=cadence_visibility_secondary"
      - "STATSD_FRONTEND_PREFIX=cadence-frontend-secondary"
      - "STATSD_MATCHING_PREFIX=cadence-matching-secondary"
      - "STATSD_HISTORY_PREFIX=cadence-history-secondary"
      - "STATSD_WORKER_PREFIX=cadence-worker-secondary"
    depends_on:
      - cassandra
      - prometheus
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
  cadence-web-secondary:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence-secondary:7933"
    ports:
      - "8089:8088"
    depends_on:
      - cadence-secondary
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
