version: '3'
services:
  cql-proxy:
    image: datastax/cql-proxy:v0.1.2
    ports:
      - "9042:9042"
    command:
      - '--astra-token=AstraCS:BwyUxZQXavLHWyQQjxQiriqA:7cb21c0bb8a0e693f5931329500683a9d7c3c896ac234b592b2b1e13d1572079'
      - '--astra-database-id=bff19ece-dcf3-4a17-8648-f92d7f00c63c'
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  cadence:
    image: ubercadence/server:master-auto-setup
    ports:
     - "8000:8000"
     - "8001:8001"
     - "8002:8002"
     - "8003:8003"
     - "7933:7933"
     - "7934:7934"
     - "7935:7935"
     - "7939:7939"
     - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=cql-proxy"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - cql-proxy
      - prometheus
  cadence-web:
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - cadence
  grafana:
    image: grafana/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'