frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.EnableConsistentQueryByDomain:
- value: true
  constraints: {}
history.enableCrossClusterOperations:
- value: true
  constraints: {}
history.enableCrossClusterOperations:
- value: true
  constraints: {}
history.useNewInitialFailoverVersion:
- value: true
  constraints: {}
