frontend.enableClientVersionCheck:
- value: true
  constraints: {}
system.minRetentionDays:
- value: 0
  constraints: {}
history.EnableConsistentQueryByDomain:
- value: true
  constraints: {}
system.enableGRPCOutbound:
- value: true
  constraints: {}
system.enableParentClosePolicyWorker:
  - value: false
    constraints: {}
system.enableWorkflowShadower:
  - value: false
    constraints: {}
system.enableFailoverManager:
  - value: false
    constraints: {}

