language: go

env:
  - CODECOV_TOKEN="d98b2209-f565-4380-a314-74e65dcb1208"

go:
  - 1.12.6
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -run=TestCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
