bench:
  name: "cadence-bench"
  domains: ["cadence-bench", "cadence-bench-sync", "cadence-bench-batch"] # it will start workers on all those domains(also try to register if not exists)
  numTaskLists: 3 # it will start workers listening on cadence-bench-tl-0, cadence-bench-tl-1,  cadence-bench-tl-2

cadence:
  service: "cadence-frontend"
  host: "127.0.0.1:7933"

metrics:
  statsd: ~
  prometheus:
    timerType: "histogram"
    listenAddress: "127.0.0.1:8004"
